version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "6500:5432"
    volumes:
      - progressDB:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  progressDB:
